server.port=8084
spring.application.name=notification-service

# The secret key the API Gateway must send
notification.api.key=NOTIFICATION-SERVICE-SECRET-KEY-2026

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# We will pass these in via Docker so you don't commit your real password to GitHub!
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true