networks:
  fms-network:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    networks:
      - fms-network

  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms_password
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - fms-network

  flight-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms_password
      POSTGRES_DB: flightdb
    volumes:
      - flight-db-data:/var/lib/postgresql/data
    networks:
      - fms-network

  booking-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms_password
      POSTGRES_DB: bookingdb
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - fms-network

  user-service:
    build: ./user-service
    container_name: user-service
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/userdb
      SPRING_DATASOURCE_USERNAME: fms
      SPRING_DATASOURCE_PASSWORD: fms_password
    networks:
      - fms-network
    depends_on:
      - user-db

  flight-service:
    build: ./flight-service
    container_name: flight-service
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://flight-db:5432/flightdb
      SPRING_DATASOURCE_USERNAME: fms
      SPRING_DATASOURCE_PASSWORD: fms_password
    networks:
      - fms-network
    depends_on:
      - flight-db

  booking-service:
    build: ./booking-service
    container_name: booking-service
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/bookingdb
      SPRING_DATASOURCE_USERNAME: fms
      SPRING_DATASOURCE_PASSWORD: fms_password
    networks:
      - fms-network
    depends_on:
      - booking-db

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - redis
      - user-service
      - flight-service
      - booking-service
    networks:
      - fms-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5500:80"
    depends_on:
      - api-gateway
    networks:
      - fms-network

volumes:
  user-db-data:
  flight-db-data:
  booking-db-data: