server.port=8082
spring.application.name=booking-service

spring.datasource.url=jdbc:h2:mem:bookingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

booking.api.key=BOOKING-SERVICE-SECRET-KEY-2026